#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

import urllib2
import json

class Suggester(object):
  def __init__(self):
    self._keyword = ''
    
  @property  
  def keyword(self):
    return self._keyword
  
  @keyword.setter
  def keyword(self, value):
    self._keyword = value
    
  @keyword.deleter
  def keyword(self):
    self._keyword = ''
    
  @property
  def suggestions(self):
    if not self._keyword:
      print 'Set keyword first'
      return []
  
    page = 'http://suggestqueries.google.com/complete/search?q=%s&client=firefox&hl=ru&ie=utf-8&oe=utf-8' % self._keyword
    search = urllib2.urlopen(page).read().decode('utf-8')
    suggestions = json.loads(search)
    return suggestions[1]
  
if __name__ == '__main__':
  s = Suggester()
  s.keyword = 'питон'
  for i in s.suggestions:
    print i
